### ISSUE TITLE
Canary deploys fail: chat image can't load pg-types after #416 layer split

### ISSUE THREAD

**Issue by aliinreallife** [Panafor-Ai-Team/Aico#417]
## Problem

Since #416 (split Docker layers) merged, the canary deploy fails at the new slot's boot migration:

```
Error: Cannot find module 'pg-types'
Require stack:
- /app/node_modules/pg/lib/defaults.js
...
- /app/docker.cjs
❌ Error during DB migration
[canary] New slot unhealthy — leaving traffic on blue
```

Run: https://github.com/Panafor-Ai-Team/Aico/actions/runs/35860094604

Blue-green kept production on `fb6b8e40` (healthy). But **every canary merge fails the same way** until this is fixed.

## Cause

The final stage copies `/deps/node_modules/{.pnpm,pg,drizzle-orm}` with `COPY --link`, which does not follow symlinks at the destination.
- In the traced standalone tree, `node_modules/pg` is a pnpm symlink into `.pnpm/`.
- The old plain `COPY` wrote through that link. `--link` replaces it with a bare directory whose sibling deps (`pg-types`, …) can't be reached.

## Also

The Docker images are only built after merge, so nothing caught this before merge. We should add a PR-time build + boot smoke test.

**Comment by aliinreallife** [comment]
Plane: [AICO-208](https://plane.panafor.com/panaforai/browse/AICO-208)
